<#
.SYNOPSIS
  Make the mesh API (a systemd service inside WSL2) come up at Windows logon.

.DESCRIPTION
  WSL2 only boots on demand, so an enabled systemd service won't run at startup
  by itself. This drops a hidden VBS launcher into the current user's Startup
  folder that, at logon, runs:
      wsl -d <Distro> -u root -- systemctl start mesh-api
  which boots WSL, lets systemd start the (enabled) service, and is a no-op if
  it is already running. No administrator rights required.

  Install the systemd unit first, from inside WSL:
      sudo bash scripts/install-mesh-service.sh install

.USAGE
  powershell -ExecutionPolicy Bypass -File scripts/install-mesh-service.ps1 [-Action install|uninstall|status] [-Distro Ubuntu]
#>
param(
  [ValidateSet('install', 'uninstall', 'status')]
  [string]$Action = 'install',
  [string]$Distro = 'Ubuntu'
)

$ErrorActionPreference = 'Stop'
$startup = [Environment]::GetFolderPath('Startup')
$vbsPath = Join-Path $startup 'PhlixMeshApi.vbs'

switch ($Action) {
  'install' {
    # 0 = hidden window, False = don't wait. Boots WSL, starts the service, then
    # holds the session open with `sleep infinity` so the WSL2 VM never idle-shuts
    # down — otherwise an incoming Tailscale request can't reach a powered-off VM.
    $vbs = @"
' Auto-generated by scripts/install-mesh-service.ps1 — starts + keeps alive the Phlix mesh API at logon.
Set sh = CreateObject("WScript.Shell")
sh.Run "wsl.exe -d $Distro -u root -- /bin/sh -c ""systemctl start mesh-api; exec sleep infinity""", 0, False
"@
    Set-Content -Path $vbsPath -Value $vbs -Encoding ASCII
    Write-Host "Installed logon launcher: $vbsPath"
    Write-Host "Runs at next sign-in. Test now without rebooting:"
    Write-Host "    wscript `"$vbsPath`""
  }
  'uninstall' {
    if (Test-Path $vbsPath) {
      Remove-Item $vbsPath -Force
      Write-Host "Removed logon launcher: $vbsPath"
    } else {
      Write-Host "No launcher at $vbsPath"
    }
  }
  'status' {
    if (Test-Path $vbsPath) { Write-Host "Installed: $vbsPath" } else { Write-Host "Not installed." }
  }
}
